FROM ruby:2.4.3
LABEL maintainer satoyuji <satoyu313@gmail.com>

ENV LANG C.UTF-8
ENV APP_ROOT /var/www
WORKDIR $APP_ROOT

# Prepare modules
RUN apt-get update -qq && \
    apt-get install -y \
    build-essential \
    libpq-dev \
    mysql-client

# Setup Rails
COPY Gemfile ${APP_ROOT}/Gemfile
COPY Gemfile.lock ${APP_ROOT}/Gemfile.lock
RUN bundle config build.nokogiri --use-system-libraries
RUN bundle install --jobs=4
